#!/bin/sh
# Gradle start up script for POSIX generated by Gradle

APP_HOME=`pwd -P`
APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

exec java -classpath $CLASSPATH org.gradle.wrapper.GradleWrapperMain "$@"
